#!/usr/bin/env bash
# *****************************************************************************
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 VNCHIP LABS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# File        : gen_mk_files.sh
# Description : TT UVM I3C simulation support file.
# Authors     : Duy Huynh, Dang Thai
# Date        : 2026-08-11
#
# *****************************************************************************

set -euo pipefail

usage() {
    cat <<'EOF'
Usage: gen_mk_files.sh [OPTIONS]

Options:
    --root <project_root>  Project root to scan. If omitted, the script walks
                                                 upward from the current directory until it finds
                                                 rtl/, sim/, and verify/.
    --rtl                  Generate sim/filelists/rtl.f only.
    -t, --t, --test        Generate sim/filelists/test.f only.
    --mk                   Generate sim/mk/paths.mk, sim/mk/incdirs.mk, and
                                                 sim/mk/srcs.mk only.
    -a, --a, --all         Generate everything: mk fragments plus both filelists.
    -h, --help             Show this help text.

If no generation option is provided, the script defaults to --mk.
EOF
}

find_project_root() {
    local start_dir="$1"
    local current_dir="$start_dir"

    while [[ "$current_dir" != "/" ]]; do
        if [[ -d "$current_dir/rtl" && -d "$current_dir/sim" && -d "$current_dir/verify" ]]; then
            printf '%s\n' "$current_dir"
            return 0
        fi
        current_dir="$(dirname "$current_dir")"
    done

    return 1
}

append_incdir() {
    local dir_path="$1"
    if [[ -d "$dir_path" ]]; then
        INC_DIRS+=("$dir_path")
    fi
}

emit_file_header() {
    local file_name="$1"
    local description="$2"

    cat <<EOF
# *****************************************************************************
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 VNCHIP LABS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# File        : $file_name
# Description : $description
# Authors     : Duy Huynh, Dang Thai
# Date        : 2026-08-11
#
# *****************************************************************************

EOF
}

generate_rtl_filelist() {
    local output_path="$1"
    local -a rtl_non_top=()
    local -a rtl_top=()
    local -a rtl_files=()
    local rtl_file

    while IFS= read -r -d '' rtl_file; do
        case "$(basename "$rtl_file")" in
            smc_peripherals_top.sv)
                # Real I3C integration is owned by the manual rtl_i3c.f list.
                continue
                ;;
            *_top.v|*_top.sv)
                rtl_top+=("$rtl_file")
                ;;
            *)
                rtl_non_top+=("$rtl_file")
                ;;
        esac
    done < <(find "$RTL_DIR" -maxdepth 1 -type f \( -name '*.v' -o -name '*.sv' \) -print0 | sort -z)

    {
        emit_file_header "$(basename "$output_path")" "Auto-generated RTL filelist."
        printf '# Auto-generated by sim/vcs_run_script/gen_mk_files.sh\n'
        printf '# Starter RTL filelist regenerated from rtl/\n\n'
        if [[ ${#rtl_non_top[@]} -gt 0 ]]; then
            for rtl_file in "${rtl_non_top[@]}"; do
                printf '../../rtl/%s\n' "$(basename "$rtl_file")"
            done
        fi
        if [[ ${#rtl_top[@]} -gt 0 ]]; then
            for rtl_file in "${rtl_top[@]}"; do
                printf '../../rtl/%s\n' "$(basename "$rtl_file")"
            done
        fi
    } > "$output_path"
}

generate_test_filelist() {
    local output_path="$1"
    local -a test_files=()
    local -a missing_tests=()
    local test_file
    local test_name
    local existing_path="$output_path"
    local burst_light="50"
    local burst_medium="20"
    local burst_heavy="10"
    local burst_extra="1"
    local burst_plan_light="seed-major"
    local burst_plan_medium="seed-major"
    local burst_plan_heavy="seed-major"
    local burst_plan_extra="seed-major"
    local raw_line
    local line
    local comment
    local current_level=""
    local has_block_format=0
    local has_light_block=0
    local temp_path=""
    local -A assigned_tests=()

    trim_value() {
        local value="$1"
        value="${value#${value%%[![:space:]]*}}"
        value="${value%${value##*[![:space:]]}}"
        printf '%s' "$value"
    }

    apply_burst_tokens() {
        local token
        for token in "$@"; do
            case "$token" in
                light=*)
                    burst_light="${token#light=}"
                    ;;
                medium=*)
                    burst_medium="${token#medium=}"
                    ;;
                heavy=*)
                    burst_heavy="${token#heavy=}"
                    ;;
                extra=*)
                    burst_extra="${token#extra=}"
                ;;
            esac
        done
    }

    apply_burst_plan_tokens() {
        local token
        local mode
        for token in "$@"; do
            case "$token" in
                light=*|medium=*|heavy=*|extra=*)
                    mode="${token#*=}"
                    case "$mode" in
                        packed|seed-major|test-major)
                            ;;
                        *)
                            mode="seed-major"
                            ;;
                    esac
                    case "$token" in
                        light=*)
                            burst_plan_light="$mode"
                            ;;
                        medium=*)
                            burst_plan_medium="$mode"
                            ;;
                        heavy=*)
                            burst_plan_heavy="$mode"
                            ;;
                        extra=*)
                            burst_plan_extra="$mode"
                            ;;
                    esac
                    ;;
            esac
        done
    }

    normalize_group_level() {
        case "${1,,}" in
            light|lite)
                printf 'light'
                ;;
            med|medium)
                printf 'medium'
                ;;
            high|heavy)
                printf 'heavy'
                ;;
            extra)
                printf 'extra'
                ;;
            *)
                printf 'light'
                ;;
        esac
    }

    append_missing_to_light_block() {
        local source_path="$1"
        local destination_path="$2"
        local current_block=""
        local inserted=0
        local new_test
        local source_line
        local stripped_line

        : > "$destination_path"
        while IFS= read -r source_line || [[ -n "$source_line" ]]; do
            source_line="${source_line%%$'\r'}"
            stripped_line="$(trim_value "$source_line")"

            if [[ "$stripped_line" =~ ^([A-Za-z0-9_.-]+)[[:space:]]*:[[:space:]]*([A-Za-z]+)[[:space:]]+([A-Za-z]+)[[:space:]]*\{$ ]]; then
                current_block="$(normalize_group_level "${BASH_REMATCH[2]}")"
            elif [[ "$stripped_line" =~ ^(light|lite|medium|med|heavy|high|extra)[[:space:]]*=[[:space:]]*\{$ ]]; then
                current_block="$(normalize_group_level "${BASH_REMATCH[1]}")"
            elif [[ "$stripped_line" == "}" ]]; then
                if [[ "$current_block" == "light" && $inserted -eq 0 && ${#missing_tests[@]} -gt 0 ]]; then
                    for new_test in "${missing_tests[@]}"; do
                        printf '%s\n' "$new_test" >> "$destination_path"
                    done
                    inserted=1
                fi
                current_block=""
            fi

            printf '%s\n' "$source_line" >> "$destination_path"
        done < "$source_path"
    }

    if [[ -f "$existing_path" ]]; then
        local -a burst_tokens=()

        while IFS= read -r raw_line || [[ -n "$raw_line" ]]; do
            raw_line="${raw_line%%$'\r'}"
            line="$(trim_value "$raw_line")"
            [[ -z "$line" ]] && continue

            if [[ "$line" == \#* ]]; then
                comment="${line#\#}"
                comment="$(trim_value "$comment")"
                if [[ "$comment" == BURST_LIMITS* ]]; then
                    comment="${comment#BURST_LIMITS}"
                    comment="$(trim_value "$comment")"
                    read -ra burst_tokens <<< "$comment"
                    apply_burst_tokens "${burst_tokens[@]}"
                elif [[ "$comment" == BURST_PLAN* ]]; then
                    comment="${comment#BURST_PLAN}"
                    comment="$(trim_value "$comment")"
                    read -ra burst_tokens <<< "$comment"
                    apply_burst_plan_tokens "${burst_tokens[@]}"
                fi
                continue
            fi

            if [[ "$line" =~ ^([A-Za-z0-9_.-]+)[[:space:]]*:[[:space:]]*([A-Za-z]+)[[:space:]]+([A-Za-z]+)[[:space:]]*\{$ ]]; then
                current_level="$(normalize_group_level "${BASH_REMATCH[2]}")"
                has_block_format=1
                if [[ "$current_level" == "light" ]]; then
                    has_light_block=1
                fi
                continue
            fi

            if [[ "$line" =~ ^(light|lite|medium|med|heavy|high|extra)[[:space:]]*=[[:space:]]*\{$ ]]; then
                current_level="$(normalize_group_level "${BASH_REMATCH[1]}")"
                has_block_format=1
                if [[ "$current_level" == "light" ]]; then
                    has_light_block=1
                fi
                continue
            fi

            if [[ "$line" == "}" ]]; then
                current_level=""
                continue
            fi

            if [[ -n "$current_level" ]]; then
                assigned_tests["$line"]=1
            fi
        done < "$existing_path"
    fi

    while IFS= read -r -d '' test_file; do
        test_name="$(basename "$test_file" .sv)"
        case "$test_name" in
            *_base_test)
                continue
                ;;
        esac
        test_files+=("$test_name")
    done < <(find "$TEST_DIR" -type f -name '*_test.sv' -print0 | sort -z)

    for test_name in "${test_files[@]}"; do
        if [[ -z "${assigned_tests[$test_name]+x}" ]]; then
            missing_tests+=("$test_name")
        fi
    done

    if [[ -f "$existing_path" && $has_block_format -eq 1 && $has_light_block -eq 1 ]]; then
        if [[ ${#missing_tests[@]} -eq 0 ]]; then
            return 0
        fi

        temp_path="$(mktemp)"
        append_missing_to_light_block "$existing_path" "$temp_path"
        mv "$temp_path" "$output_path"
        return 0
    fi

    {
        emit_file_header "$(basename "$output_path")" "Auto-generated regression test list."
        printf '# Auto-generated by sim/vcs_run_script/gen_mk_files.sh\n'
        printf '# Starter regression test list regenerated from verify/tb/tests/\n'
        printf '# Format:\n'
        printf '# BURST_LIMITS light=%s medium=%s heavy=%s extra=%s\n' \
            "$burst_light" "$burst_medium" "$burst_heavy" "$burst_extra"
        printf '# BURST_PLAN light=%s medium=%s heavy=%s extra=%s\n' \
            "$burst_plan_light" "$burst_plan_medium" "$burst_plan_heavy" "$burst_plan_extra"
        printf '# Supported burst plan values: seed-major, packed, test-major\n'
        printf '#   seed-major = finish all selected tests for one seed before the next seed\n'
        printf '#   packed     = planner may group multiple tests/seeds in one burst for throughput\n'
        printf '#   test-major = finish one test across its seed chunks before the next test\n'
        printf '# Regression group format:\n'
        printf '#   <label> : <level> <on/off> {\n'
        printf '#   test_name\n'
        printf '# }\n'
        printf '# label must be unique. level accepts light, medium/med, heavy/high, extra.\n'
        printf '# off groups are skipped by --all and level selection.\n'
        printf '# Metadata comments are parsed; other comment lines are ignored.\n\n'
        printf 'auto : light on {\n'
        for test_name in "${test_files[@]}"; do
            printf '%s\n' "$test_name"
        done
        printf '}\n'
    } > "$output_path"
}

write_list_block() {
    local output_path="$1"
    local variable_name="$2"
    shift 2
    local -a items=("$@")

    {
        emit_file_header "$(basename "$output_path")" "Auto-generated makefile fragment."
        printf '# Auto-generated by sim/vcs_run_script/gen_mk_files.sh\n\n'
        printf '%s := \\\n' "$variable_name"
        local item_index=0
        local item_count=${#items[@]}
        for item in "${items[@]}"; do
            item_index=$((item_index + 1))
            if [[ $item_index -lt $item_count ]]; then
                printf '    %s \\\n' "$item"
            else
                printf '    %s\n' "$item"
            fi
        done
    } > "$output_path"
}

ROOT_DIR_INPUT=""
GENERATE_MK=0
GENERATE_RTL=0
GENERATE_TEST=0
GENERATE_ALL=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --root)
            ROOT_DIR_INPUT="${2:-}"
            shift 2
            ;;
        --rtl)
            GENERATE_RTL=1
            shift
            ;;
        -t|--t|--test)
            GENERATE_TEST=1
            shift
            ;;
        --mk)
            GENERATE_MK=1
            shift
            ;;
        -a|--a|--all)
            GENERATE_ALL=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[ERROR] Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

if [[ $GENERATE_ALL -eq 1 ]]; then
    GENERATE_MK=1
    GENERATE_RTL=1
    GENERATE_TEST=1
fi

if [[ $GENERATE_MK -eq 0 && $GENERATE_RTL -eq 0 && $GENERATE_TEST -eq 0 ]]; then
    GENERATE_MK=1
fi

if [[ -n "$ROOT_DIR_INPUT" ]]; then
    ROOT_DIR="$(cd "$ROOT_DIR_INPUT" && pwd)"
else
    ROOT_DIR="$(find_project_root "$PWD")"
fi

SIM_DIR="$ROOT_DIR/sim"
MK_DIR="$SIM_DIR/mk"
FILELIST_DIR="$SIM_DIR/filelists"
RTL_DIR="$ROOT_DIR/rtl"
TEST_DIR="$ROOT_DIR/verify/tb/tests"

mkdir -p "$MK_DIR"
mkdir -p "$FILELIST_DIR"

if [[ $GENERATE_MK -eq 1 ]]; then
{
emit_file_header "paths.mk" "Auto-generated simulation paths makefile fragment."
cat <<EOF
# Auto-generated by sim/vcs_run_script/gen_mk_files.sh

ROOT_DIR     := \$(abspath \$(SIM_MAKEFILE_DIR)/..)
SIM_DIR      := \$(SIM_MAKEFILE_DIR)
SCRIPTS_DIR  := \$(SIM_DIR)/vcs_run_script
RTL_DIR      := \$(ROOT_DIR)/rtl
VERIFY_DIR   := \$(ROOT_DIR)/verify
VIP_DIR      := \$(VERIFY_DIR)/vip
TB_DIR       := \$(VERIFY_DIR)/tb
CHECKERS_DIR := \$(VERIFY_DIR)/checkers
LOG_DIR      := logs
FILELIST_DIR := \$(SIM_DIR)/filelists
RTL_FLIST    := \$(FILELIST_DIR)/rtl.f
TEST_FLIST   := \$(FILELIST_DIR)/test.f
EOF
} > "$MK_DIR/paths.mk"
fi

if [[ $GENERATE_MK -eq 1 ]]; then

# ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ incdirs.mk ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬
# Dynamically scan verify/ and rtl/ for include-worthy directories.
INC_DIRS=()

# RTL directory
[[ -d "$ROOT_DIR/rtl" ]] && INC_DIRS+=("../../rtl")

# VIP: top-level dirs + sub-directories (if, core, agent, sequences, coverage,
# analysis, env, sva)
while IFS= read -r -d '' d; do
    INC_DIRS+=("../../${d#"$ROOT_DIR/"}")
done < <(find "$ROOT_DIR/verify/vip" -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null | sort -z)

while IFS= read -r -d '' d; do
    INC_DIRS+=("../../${d#"$ROOT_DIR/"}")
done < <(find "$ROOT_DIR/verify/vip" -mindepth 2 -type d \( -name if -o -name core -o -name agent -o -name sequence -o -name sequences -o -name coverage -o -name analysis -o -name env -o -name sva \) -print0 2>/dev/null | sort -z)

# Checkers: top-level dirs + sub-directories
while IFS= read -r -d '' d; do
    INC_DIRS+=("../../${d#"$ROOT_DIR/"}")
done < <(find "$ROOT_DIR/verify/checkers" -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null | sort -z)

while IFS= read -r -d '' d; do
    INC_DIRS+=("../../${d#"$ROOT_DIR/"}")
done < <(find "$ROOT_DIR/verify/checkers" -mindepth 2 -type d \( -name if -o -name core -o -name agent -o -name sva \) -print0 2>/dev/null | sort -z)

# TB sub-directories. Env-owned reusable contracts, adapters, services, and
# IP wrapper implementations are grouped recursively below verify/tb/env.
for tb_sub in ral coverage env sequences tests top sva vseq; do
    [[ -d "$ROOT_DIR/verify/tb/$tb_sub" ]] && INC_DIRS+=("../../verify/tb/$tb_sub")
done

while IFS= read -r -d '' d; do
    INC_DIRS+=("../../${d#"$ROOT_DIR/"}")
done < <(find "$ROOT_DIR/verify/tb/env" -mindepth 1 -type d -print0 2>/dev/null | sort -z)

while IFS= read -r -d '' d; do
    INC_DIRS+=("../../${d#"$ROOT_DIR/"}")
done < <(find "$ROOT_DIR/verify/tb/coverage" -mindepth 1 -type d -print0 2>/dev/null | sort -z)

while IFS= read -r -d '' d; do
    INC_DIRS+=("../../${d#"$ROOT_DIR/"}")
done < <(find "$ROOT_DIR/verify/tb/vseq" -mindepth 1 -type d -print0 2>/dev/null | sort -z)

while IFS= read -r -d '' d; do
    INC_DIRS+=("../../${d#"$ROOT_DIR/"}")
done < <(find "$ROOT_DIR/verify/tb/tests" -mindepth 1 -type d -print0 2>/dev/null | sort -z)

while IFS= read -r -d '' d; do
    INC_DIRS+=("../../${d#"$ROOT_DIR/"}")
done < <(find "$ROOT_DIR/verify/tb/sequences" -mindepth 1 -type d -print0 2>/dev/null | sort -z)

while IFS= read -r -d '' d; do
    INC_DIRS+=("../../${d#"$ROOT_DIR/"}")
done < <(find "$ROOT_DIR/verify/tb/sva" -mindepth 1 -type d -print0 2>/dev/null | sort -z)

{
    emit_file_header "incdirs.mk" "Auto-generated include-directory makefile fragment."
    printf '# Auto-generated by sim/vcs_run_script/gen_mk_files.sh\n\n'
    printf 'INCDIRS := \\\n'
    for index in "${!INC_DIRS[@]}"; do
        if [[ "$index" -lt "$(( ${#INC_DIRS[@]} - 1 ))" ]]; then
            printf '    +incdir+%s \\\n' "$(printf '%s' "${INC_DIRS[$index]}" | sed 's#^\.\./\.\./#$(ROOT_DIR)/#')"
        else
            printf '    +incdir+%s\n' "$(printf '%s' "${INC_DIRS[$index]}" | sed 's#^\.\./\.\./#$(ROOT_DIR)/#')"
        fi
    done
} > "$MK_DIR/incdirs.mk"

# ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ srcs.mk ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬ÃƒÂ¢Ã¢â‚¬ÂÃ¢â€šÂ¬
# Dynamically scan verify/ to discover source files grouped by compilation
# order category. Output Make fragments use ROOT_DIR-anchored paths so
# compilation can run from isolated build directories.

to_mk_rel() { printf '%s' "../../${1#"$ROOT_DIR/"}"; }

mk_root_expr_from_rel() { printf '%s' "\$(ROOT_DIR)/${1#../../}"; }

# Helper: collect .sv files from find into a named array (bash 3.x compatible)
collect_files() {
    local _arr_name="$1"
    shift
    local -a raw_cmd=("$@")
    local -a filtered_cmd=()
    local -a find_roots=()
    local idx=0
    local f

    if [[ "${raw_cmd[0]:-}" == "find" ]]; then
        filtered_cmd+=("find")
        for ((idx = 1; idx < ${#raw_cmd[@]}; idx++)); do
            if [[ "${raw_cmd[$idx]}" == -* ]] || [[ "${raw_cmd[$idx]}" == "!" ]] || [[ "${raw_cmd[$idx]}" == "(" ]] || [[ "${raw_cmd[$idx]}" == ")" ]]; then
                break
            fi
            if [[ -e "${raw_cmd[$idx]}" ]]; then
                find_roots+=("${raw_cmd[$idx]}")
            fi
        done

        if [[ ${#find_roots[@]} -eq 0 ]]; then
            return 0
        fi

        filtered_cmd+=("${find_roots[@]}")
        for ((; idx < ${#raw_cmd[@]}; idx++)); do
            filtered_cmd+=("${raw_cmd[$idx]}")
        done
    else
        filtered_cmd=("${raw_cmd[@]}")
    fi

    while IFS= read -r -d '' f; do
        eval "${_arr_name}+=(\"$(to_mk_rel "$f")\")"
    done < <("${filtered_cmd[@]}" | sort -z)
}

from_mk_rel() {
    printf '%s' "$ROOT_DIR/${1#../../}"
}

extract_pkg_name() {
    local pkg_file="$1"
    awk '
        /^[[:space:]]*package[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*;/ {
            name = $2
            sub(/;.*/, "", name)
            print name
            exit
        }
    ' "$pkg_file"
}

extract_pkg_imports() {
    local pkg_file="$1"
    awk '
        /^[[:space:]]*import[[:space:]]+[A-Za-z_][A-Za-z0-9_]*::\*[[:space:]]*;/ {
            dep = $2
            sub(/::.*/, "", dep)
            if (dep != "uvm_pkg") {
                print dep
            }
        }
    ' "$pkg_file"
}

topo_sort_pkg_files() {
    local input_arr_name="$1"
    local output_arr_name="$2"
    local -a input_files=()
    local -a ordered_files=()
    local -a deps=()
    local mk_file
    local abs_file
    local pkg_name
    local dep
    local dep_key
    local dep_list
    local output_count=0
    local total_count=0
    local progress=0
    local ready=0

    eval "input_files=(\"\${${input_arr_name}[@]}\")"

    declare -A file_pkg_name=()
    declare -A pkg_name_to_file=()
    declare -A emitted_file=()
    declare -A emitted_pkg=()
    declare -A file_deps=()

    for mk_file in "${input_files[@]}"; do
        abs_file="$(from_mk_rel "$mk_file")"
        pkg_name="$(extract_pkg_name "$abs_file")"
        if [[ -z "$pkg_name" ]]; then
            echo "[ERROR] Failed to detect package name in: $abs_file" >&2
            exit 1
        fi
        if [[ -n "${pkg_name_to_file[$pkg_name]+x}" ]]; then
            echo "[ERROR] Duplicate package name '$pkg_name' in:" >&2
            echo "        ${pkg_name_to_file[$pkg_name]}" >&2
            echo "        $mk_file" >&2
            exit 1
        fi
        file_pkg_name["$mk_file"]="$pkg_name"
        pkg_name_to_file["$pkg_name"]="$mk_file"
    done

    for mk_file in "${input_files[@]}"; do
        abs_file="$(from_mk_rel "$mk_file")"
        dep_list=""
        while IFS= read -r dep; do
            if [[ -n "${pkg_name_to_file[$dep]+x}" ]]; then
                dep_key=" $dep "
                if [[ "$dep_list" != *"$dep_key"* ]]; then
                    dep_list="${dep_list}${dep} "
                fi
            fi
        done < <(extract_pkg_imports "$abs_file")
        file_deps["$mk_file"]="$dep_list"
    done

    total_count=${#input_files[@]}
    while [[ $output_count -lt $total_count ]]; do
        progress=0
        for mk_file in "${input_files[@]}"; do
            [[ -n "${emitted_file[$mk_file]+x}" ]] && continue
            ready=1
            for dep in ${file_deps[$mk_file]}; do
                if [[ -z "${emitted_pkg[$dep]+x}" ]]; then
                    ready=0
                    break
                fi
            done
            if [[ $ready -eq 1 ]]; then
                ordered_files+=("$mk_file")
                emitted_file["$mk_file"]=1
                emitted_pkg["${file_pkg_name[$mk_file]}"]=1
                output_count=$((output_count + 1))
                progress=1
            fi
        done

        if [[ $progress -eq 0 ]]; then
            echo "[ERROR] Could not resolve package compilation order." >&2
            for mk_file in "${input_files[@]}"; do
                if [[ -z "${emitted_file[$mk_file]+x}" ]]; then
                    echo "        pending: ${file_pkg_name[$mk_file]} <- ${file_deps[$mk_file]}" >&2
                fi
            done
            exit 1
        fi
    done

    eval "${output_arr_name}=()"
    for mk_file in "${ordered_files[@]}"; do
        eval "${output_arr_name}+=(\"\$mk_file\")"
    done
}

# 1) TB core packages: *_params_pkg.sv only
TB_CORE_PKG=()
collect_files TB_CORE_PKG find "$ROOT_DIR/verify/tb/top" -maxdepth 1 -name '*_params_pkg.sv' -print0
collect_files TB_CORE_PKG find "$ROOT_DIR/verify/tb/top" -maxdepth 1 -name '*_report_pkg.sv' -print0

# 2) VIP + Checker interface files (*/if/*.sv)
VIP_IF=()
# The I3C VIP has a package/interface dependency cycle inherited from its
# backend, so sim/mk/i3c.mk owns its explicit types -> interface -> package
# ordering. Do not add its interface again through the generic VIP scan.
collect_files VIP_IF find "$ROOT_DIR/verify/vip" "$ROOT_DIR/verify/checkers" \
    -path "$ROOT_DIR/verify/vip/i3c_vip" -prune -o \
    -path '*/if/*.sv' -print0
# 3) SVA files: tb-owned common helper/package files first, then
#    TB-only IP/integration trees, reusable VIP/checker SVA
#    packages/modules, and finally the shared bind module.
SVA=()
[[ -d "$ROOT_DIR/verify/tb/sva/common" ]] && \
    collect_files SVA find "$ROOT_DIR/verify/tb/sva/common" -maxdepth 1 -name '*.sv' ! -name 'sva_bind.sv' -print0
[[ -d "$ROOT_DIR/verify/tb/sva/ip" ]] && \
    collect_files SVA find "$ROOT_DIR/verify/tb/sva/ip" -maxdepth 1 -name '*.sv' -print0
[[ -d "$ROOT_DIR/verify/tb/sva/integration" ]] && \
    collect_files SVA find "$ROOT_DIR/verify/tb/sva/integration" -maxdepth 1 -name '*.sv' -print0
collect_files SVA find "$ROOT_DIR/verify/vip" "$ROOT_DIR/verify/checkers" -path '*/sva/*_pkg.sv' -print0
collect_files SVA find "$ROOT_DIR/verify/vip" "$ROOT_DIR/verify/checkers" -path '*/sva/*.sv' ! -name '*_pkg.sv' -print0
if [[ -f "$ROOT_DIR/verify/tb/sva/bind/sva_bind.sv" ]]; then
    SVA+=("$(to_mk_rel "$ROOT_DIR/verify/tb/sva/bind/sva_bind.sv")")
fi

# 4) TB RAL packages
TB_RAL_PKG=()
collect_files TB_RAL_PKG find "$ROOT_DIR/verify/tb/ral" -maxdepth 1 -name '*_pkg.sv' -print0

# 5) VIP packages (top-level *_pkg.sv in each VIP)
VIP_PKG=()
# The I3C package is emitted by i3c_vip.mk after its interface.
collect_files VIP_PKG find "$ROOT_DIR/verify/vip" \
    -maxdepth 2 \
    -path "$ROOT_DIR/verify/vip/i3c_vip" -prune -o \
    -name '*_pkg.sv' -print0
# 6) Checker packages
CHECKER_PKG=()
collect_files CHECKER_PKG find "$ROOT_DIR/verify/checkers" -maxdepth 2 -name '*_pkg.sv' -print0

# 7) TB coverage packages
TB_COV_PKG=()
collect_files TB_COV_PKG find "$ROOT_DIR/verify/tb/coverage" -maxdepth 1 -name '*_pkg.sv' -print0

# 8) TB env packages (env_cfg, env components, local scoreboards,
#    and vseq context/service objects)
TB_ENV_PKG=()
collect_files TB_ENV_PKG find "$ROOT_DIR/verify/tb/env" -maxdepth 1 -name '*_pkg.sv' -print0

# 9) TB vseq package. The package lives under verify/tb/vseq as the
#    single entrypoint; its implementations are grouped below
#    vseq/core, vseq/integration, and vseq/ip_only.
TB_VSEQ_PKG=()
collect_files TB_VSEQ_PKG find "$ROOT_DIR/verify/tb/vseq" -maxdepth 1 -name '*_pkg.sv' -print0

# 10) TB test packages. Keep package entrypoints at verify/tb/tests root;
#     implementation test classes are grouped in tests/core,
#     tests/integration, and tests/ip_only.
TB_TEST_PKG=()
collect_files TB_TEST_PKG find "$ROOT_DIR/verify/tb/tests" -maxdepth 1 -name '*_pkg.sv' -print0

# Bash versions before 4.4 treat an initialized empty array as unbound when it
# is expanded under nounset. Package groups are intentionally optional, so
# relax nounset only while aggregating and emitting these arrays.
set +u

# Resolve non-param package compilation order from explicit package imports.
ORDERED_PKG=("${TB_RAL_PKG[@]}")
ORDERED_PKG+=("${VIP_PKG[@]}")
ORDERED_PKG+=("${CHECKER_PKG[@]}")
ORDERED_PKG+=("${TB_COV_PKG[@]}")
ORDERED_PKG+=("${TB_ENV_PKG[@]}")
ORDERED_PKG+=("${TB_VSEQ_PKG[@]}")
ORDERED_PKG+=("${TB_TEST_PKG[@]}")
topo_sort_pkg_files ORDERED_PKG ORDERED_PKG

# 11) TB top files (tb_*_top.sv, excluding sva_bind.sv)
TB_TOP=()
collect_files TB_TOP find "$ROOT_DIR/verify/tb/top" -maxdepth 1 -name 'tb_*_top.sv' -print0

# Helper: emit a Makefile variable assignment to stdout
emit_mk_var() {
    local variable_name="$1"
    shift
    local -a items=("$@")
    local item_count=${#items[@]}
    if [[ $item_count -eq 0 ]]; then
        printf '%s :=\n' "$variable_name"
        return
    fi
    printf '%s := \\\n' "$variable_name"
    local i=0
    local item_expr=""
    for item in "${items[@]}"; do
        i=$((i + 1))
        item_expr="$(mk_root_expr_from_rel "$item")"
        if [[ $i -lt $item_count ]]; then
            printf '    %s \\\n' "$item_expr"
        else
            printf '    %s\n' "$item_expr"
        fi
    done
}

{
    emit_file_header "srcs.mk" "Auto-generated source-list makefile fragment."
    printf '# Auto-generated by sim/vcs_run_script/gen_mk_files.sh\n\n'

    emit_mk_var "TB_CORE_PKG_SRC_FILES" "${TB_CORE_PKG[@]}"
    printf '\n'
    emit_mk_var "VIP_IF_SRC_FILES" "${VIP_IF[@]}"
    printf '\n'
    emit_mk_var "TB_RAL_PKG_SRC_FILES" "${TB_RAL_PKG[@]}"
    printf '\n'
    emit_mk_var "VIP_PKG_SRC_FILES" "${VIP_PKG[@]}"
    printf '\n'
    emit_mk_var "CHECKER_PKG_SRC_FILES" "${CHECKER_PKG[@]}"
    printf '\n'
    emit_mk_var "TB_COV_PKG_SRC_FILES" "${TB_COV_PKG[@]}"
    printf '\n'
    emit_mk_var "TB_ENV_PKG_SRC_FILES" "${TB_ENV_PKG[@]}"
    printf '\n'
    emit_mk_var "TB_VSEQ_PKG_SRC_FILES" "${TB_VSEQ_PKG[@]}"
    printf '\n'
    emit_mk_var "TB_TEST_PKG_SRC_FILES" "${TB_TEST_PKG[@]}"
    printf '\n'
    emit_mk_var "ORDERED_PKG_SRC_FILES" "${ORDERED_PKG[@]}"
    printf '\n'
    emit_mk_var "SVA_SRC_FILES" "${SVA[@]}"
    printf '\n'
    emit_mk_var "TB_TOP_SRC_FILES" "${TB_TOP[@]}"
    printf '\n'
    printf 'RTL_SRC_FILES := -f $(RTL_FLIST)\n'
    printf '\n'
    printf 'SRC_FILES := \\\n'
    printf '    $(TB_CORE_PKG_SRC_FILES) \\\n'
    printf '    $(VIP_IF_SRC_FILES) \\\n'
    printf '    $(ORDERED_PKG_SRC_FILES) \\\n'
    printf '    $(SVA_SRC_FILES) \\\n'
    printf '    $(TB_TOP_SRC_FILES) \\\n'
    printf '    $(RTL_SRC_FILES)\n'
} > "$MK_DIR/srcs.mk"
set -u
fi

if [[ $GENERATE_RTL -eq 1 ]]; then
    generate_rtl_filelist "$FILELIST_DIR/rtl.f"
fi

if [[ $GENERATE_TEST -eq 1 ]]; then
    generate_test_filelist "$FILELIST_DIR/test.f"
fi

if [[ -f "$ROOT_DIR/rtl/external/i3c_core.f" ]]; then
    for manual_file in \
        "$FILELIST_DIR/rtl_i3c.f" \
        "$MK_DIR/i3c.mk" \
        "$MK_DIR/i3c_child_srcs.mk"; do
        if [[ ! -s "$manual_file" ]]; then
            echo "[ERROR] Missing manual I3C integration file: $manual_file" >&2
            exit 1
        fi
    done
fi

# Progress echo suppressed to keep startup output compact.
: # Generated dynamic mk fragments/filelists for: $ROOT_DIR
