#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="${DV_PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
SIM_DIR="$PROJECT_ROOT/sim"
GENERATED_DIR="$SIM_DIR/generated"
SOURCE_TESTPLAN="$SIM_DIR/filelists/test.f"
OUTPUT_TESTPLAN="$GENERATED_DIR/testplan.dv"
OUTPUT_FILELIST="$GENERATED_DIR/compile.f"
DUT_MODE="${DUT_MODE:-rtl}"
GENERATION_LOCK="$GENERATED_DIR/.generate.lock"
GENERATION_LOCK_DIR="$GENERATED_DIR/.generate.lock.d"
OUTPUT_FILELIST_TMP="$OUTPUT_FILELIST.tmp.$$"
OUTPUT_TESTPLAN_TMP="$OUTPUT_TESTPLAN.tmp.$$"
FALLBACK_LOCK_HELD=0

mkdir -p "$GENERATED_DIR"

cleanup_generation() {
    rm -f "$OUTPUT_FILELIST_TMP" "$OUTPUT_TESTPLAN_TMP"
    if ((FALLBACK_LOCK_HELD)); then
        rmdir "$GENERATION_LOCK_DIR" 2>/dev/null || true
    fi
}
trap cleanup_generation EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

# Preflight runs once per parallel burst. Serialize all generated and tracked
# filelist writes so concurrent bursts cannot consume each other's temp files.
if command -v flock >/dev/null 2>&1; then
    exec 9>"$GENERATION_LOCK"
    flock 9
else
    generation_wait=0
    until mkdir "$GENERATION_LOCK_DIR" 2>/dev/null; do
        generation_wait=$((generation_wait + 1))
        if ((generation_wait >= 300)); then
            printf '[ERROR] Timed out waiting for DV input generation lock: %s\n' "$GENERATION_LOCK_DIR" >&2
            exit 1
        fi
        sleep 1
    done
    FALLBACK_LOCK_HELD=1
fi

"$SIM_DIR/scripts/gen_mk_files.sh" --root "$PROJECT_ROOT" --all

{
    printf '# Generated by sim/project/generate_dv_inputs.sh; do not edit.\n'
    make -s -C "$PROJECT_ROOT" -f "$SIM_DIR/project/i3c_inputs.mk" \
        DUT_MODE="$DUT_MODE" emit-compile-filelist
} > "$OUTPUT_FILELIST_TMP"
mv "$OUTPUT_FILELIST_TMP" "$OUTPUT_FILELIST"

awk '
    BEGIN {
        print "# DV_TESTPLAN_VERSION=2"
        print "# test|case_id|group|level|enabled|seed_policy|default_seeds|plusargs|tags|compile_requirements"
        group=""; level=""; enabled=""
    }
    /^[[:space:]]*#[[:space:]]*TEST_REQUIRES_COMPILE[[:space:]]+/ {
        line=$0
        sub(/^[[:space:]]*#[[:space:]]*TEST_REQUIRES_COMPILE[[:space:]]+/, "", line)
        split(line, fields, "=")
        requirement_test=fields[1]
        gsub(/[[:space:]]/, "", requirement_test)
        requirement_value=substr(line, index(line, "=") + 1)
        gsub(/[[:space:]]/, "", requirement_value)
        if (requirement_test != "" && requirement_value != "")
            compile_requirements[requirement_test]=requirement_value
        next
    }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    /^[[:space:]]*[A-Za-z0-9_.-]+[[:space:]]*:[[:space:]]*[A-Za-z0-9_.-]+[[:space:]]+(on|off)[[:space:]]*\{/ {
        line=$0
        sub(/^[[:space:]]*/, "", line)
        split(line, fields, /[[:space:]]+/)
        group=fields[1]
        level=fields[3]
        enabled=fields[4]
        next
    }
    /^[[:space:]]*\}/ { group=""; next }
    group != "" {
        entry=$0
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", entry)
        field_count=split(entry, entry_fields, /[[:space:]]*\|[[:space:]]*/)
        test=entry_fields[1]
        case_id=(field_count >= 2 ? entry_fields[2] : "")
        entry_plusargs=(field_count >= 3 ? entry_fields[3] : "")
        if (field_count > 3 || test !~ /^[A-Za-z0-9_.-]+$/ ||
            case_id !~ /^$|^[A-Za-z0-9_.-]+$/) {
            print "Invalid per-entry testplan row: " entry > "/dev/stderr"
            exit 2
        }
        if (case_id == "") case_id=test
        plusargs=entry_plusargs
        tags="generated"
        coverage_required = (group == "i3c_ibi_coverage" ||
                             group == "i3c_ibi_random" ||
                             group == "i3c_ibi_legacy_aliases" ||
                             group ~ /^i3c_ibi_multi_target_/)
        if (group == "i3c_ibi_wip" &&
            test !~ /reset_flush|invalid_target|busy_bus_block/)
            coverage_required = 1
        if (coverage_required) {
            plusargs=plusargs (plusargs == "" ? "" : " ") "+IBI_REQUIRE_COV"
            tags=tags ",coverage,coverage-required"
        }
        else if (group == "i3c_ibi_rtl_unsupported")
            tags=tags ",rtl-unsupported,coverage-exempt"
        else if (test ~ /reset_flush|invalid_target|busy_bus_block|soft_rst_selfclear/)
            tags=tags ",coverage-exempt"
        if (group == "i3c_ibi_random")
            tags=tags ",random-seed"
        else
            tags=tags ",coverage-iteration=once"
        # Directed scenarios are deterministic and remain one-seed by default.
        # Random-tagged scenarios get a reproducible five-seed baseline.
        # Explicit --seeds overrides every selected entry, while --rand-num
# only replaces seeds on entries carrying the random-seed tag.
        default_seeds=(group == "i3c_ibi_random") ? "1,2,3,4,5" : "1"
        print test "|" case_id "|" group "|" level "|" enabled "|all|" default_seeds "|" plusargs "|" tags "|" compile_requirements[test]
    }
' "$SOURCE_TESTPLAN" > "$OUTPUT_TESTPLAN_TMP"
mv "$OUTPUT_TESTPLAN_TMP" "$OUTPUT_TESTPLAN"

# Progress echoes suppressed to keep startup output compact; the generated
# artifacts remain at $OUTPUT_FILELIST and $OUTPUT_TESTPLAN.
