#!/usr/bin/env bash
# *****************************************************************************
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 VNCHIP LABS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# File        : generate_dv_inputs.sh
# Description : TT UVM I3C simulation support file.
# Authors     : Duy Huynh, Dang Thai
# Date        : 2026-08-11
#
# *****************************************************************************


set -euo pipefail

PROJECT_ROOT="${DV_PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
SIM_DIR="$PROJECT_ROOT/sim"
GENERATED_DIR="$SIM_DIR/generated"
SOURCE_TESTPLAN="$SIM_DIR/filelists/test.f"
OUTPUT_TESTPLAN="$GENERATED_DIR/testplan.dv"
OUTPUT_FILELIST="$GENERATED_DIR/compile.f"
DUT_MODE="${DUT_MODE:-rtl}"
OUTPUT_FILELIST_TMP=''
OUTPUT_TESTPLAN_TMP=''

mkdir -p "$GENERATED_DIR"
OUTPUT_FILELIST_TMP="$(mktemp "$GENERATED_DIR/.compile.f.XXXXXX")"
OUTPUT_TESTPLAN_TMP="$(mktemp "$GENERATED_DIR/.testplan.dv.XXXXXX")"
trap 'rm -f "$OUTPUT_FILELIST_TMP" "$OUTPUT_TESTPLAN_TMP"' EXIT
"$SIM_DIR/vcs_run_script/gen_mk_files.sh" --all

{
    printf '# Generated by sim/project/generate_dv_inputs.sh; do not edit.\n'
    make -s -C "$PROJECT_ROOT" -f "$SIM_DIR/project/i3c_inputs.mk" \
        DUT_MODE="$DUT_MODE" emit-compile-filelist
} > "$OUTPUT_FILELIST_TMP"
mv -f "$OUTPUT_FILELIST_TMP" "$OUTPUT_FILELIST"
OUTPUT_FILELIST_TMP=''

awk '
    BEGIN {
        print "# DV_TESTPLAN_VERSION=1"
        print "# test|group|level|enabled|seed_policy|default_seeds|plusargs|tags"
        group=""; level=""; enabled=""
    }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    /^[[:space:]]*[A-Za-z0-9_.-]+[[:space:]]*:[[:space:]]*[A-Za-z0-9_.-]+[[:space:]]+(on|off)[[:space:]]*\{/ {
        line=$0
        sub(/^[[:space:]]*/, "", line)
        split(line, fields, /[[:space:]]+/)
        group=fields[1]
        level=fields[3]
        enabled=fields[4]
        next
    }
    /^[[:space:]]*\}/ { group=""; next }
    group != "" {
        test=$0
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", test)
        plusargs=""
        tags="generated"
        if (group == "i3c_ibi_coverage") {
            plusargs="+IBI_REQUIRE_COV"
            tags=tags ",coverage"
        }
        else if (group == "i3c_ibi_rtl_defects") {
            tags=tags ",rtl-defect"
        }
        print test "|" group "|" level "|" enabled "|all|1|" plusargs "|" tags
    }
' "$SOURCE_TESTPLAN" > "$OUTPUT_TESTPLAN_TMP"
mv -f "$OUTPUT_TESTPLAN_TMP" "$OUTPUT_TESTPLAN"
OUTPUT_TESTPLAN_TMP=''

# Progress echoes suppressed to keep startup output compact; the generated
# artifacts remain at $OUTPUT_FILELIST and $OUTPUT_TESTPLAN.
