# *****************************************************************************
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 VNCHIP LABS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# File        : axi4lite_vip.mk
# Description : Build variables and source lists for the AXI4-Lite VIP.
# Authors     : Huynh Pham Anh Duy, Thai Hai Dang
# Date        : 2026-07-28
#
# *****************************************************************************

# Auto-generated by sim/scripts/gen_mk_files.sh

AXI4LITE_VIP_MK_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
AXI4LITE_VIP_DIR ?= $(AXI4LITE_VIP_MK_DIR)

AXI4LITE_VIP_INCDIRS := \
    +incdir+$(AXI4LITE_VIP_DIR) \
    +incdir+$(AXI4LITE_VIP_DIR)/agent \
    +incdir+$(AXI4LITE_VIP_DIR)/core \
    +incdir+$(AXI4LITE_VIP_DIR)/if \
    +incdir+$(AXI4LITE_VIP_DIR)/sequences

AXI4LITE_VIP_IF_SRC_FILES := \
    $(AXI4LITE_VIP_DIR)/if/axi4lite_if.sv

AXI4LITE_VIP_PKG_SRC_FILES := \
    $(AXI4LITE_VIP_DIR)/axi4lite_vip_pkg.sv
