#!/usr/bin/env bash

runner_info() { printf '[INFO] %s\n' "$*"; }
runner_note() { printf '[NOTE] %s\n' "$*"; }
runner_warn() { printf '[WARNING] %s\n' "$*" >&2; }
runner_error() { printf '[ERROR] %s\n' "$*" >&2; }
runner_die() { runner_error "$*"; return 2; }

# Color only human-facing status tokens. Machine-readable artifacts never call
# this helper, and auto mode disables ANSI when stdout is redirected or piped.
runner_color_enabled() {
    [[ -z "${NO_COLOR:-}" ]] || return 1
    [[ "${TERM:-}" != dumb ]] || return 1
    [[ -t "${1:-1}" ]]
}

runner_status_token() {
    local status="$1"
    if runner_color_enabled 1; then
        case "$status" in
            PASS) printf '\033[32m[PASS]\033[0m' ;;
            FAIL) printf '\033[31m[FAIL]\033[0m' ;;
            *) printf '[%s]' "$status" ;;
        esac
    else
        printf '[%s]' "$status"
    fi
}

runner_panel_begin() {
    printf '\n================================================================================\n'
    printf '  %s\n' "$1"
    printf '================================================================================\n'
}

runner_panel_value() {
    printf ' %-18s : %s\n' "$1" "${2:--}"
}

runner_panel_end() { printf '================================================================================\n'; }

runner_timestamp() { date '+%Y%m%d_%H%M%S'; }
runner_display_time() { date '+%Y-%m-%d Time %H:%M:%S %z'; }

RUNNER_SCOREBOARD_FAILURE_REGEX="${RUNNER_SCOREBOARD_FAILURE_REGEX:-scoreboard[[:space:]_-]+(fail(ed|ure)?|mismatch)|scoreboard.*mismatch(es)?[[:space:]]*[:=][[:space:]]*[1-9][0-9]*|[[:alnum:]_]*SB_(FAIL|ERROR|MISMATCH)[[:alnum:]_]*}"
RUNNER_UVM_FAILURE_REGEX="${RUNNER_UVM_FAILURE_REGEX:-UVM_(ERROR|FATAL)[[:space:]]*:[[:space:]]*[1-9][0-9]*|UVM_(ERROR|FATAL)[[:space:]]+[@/]}"
RUNNER_PLAIN_ERROR_REGEX="${RUNNER_PLAIN_ERROR_REGEX:-^[[:space:]]*(Error:|Fatal:|\\[ERROR\\])|^[[:space:]]*Error-\\[[A-Z0-9_-]+\\]}"
RUNNER_UVM_EVENT_REGEX="${RUNNER_UVM_EVENT_REGEX:-UVM_(ERROR|FATAL)[[:space:]]+[@/]|^[[:space:]]*(ERROR|FATAL)[[:space:]]+@}"

runner_new_id() {
    local prefix="${1:-run}"
    printf '%s_%s_%s\n' "$prefix" "$(runner_timestamp)" "$$"
}

runner_sanitize_token() {
    printf '%s' "$1" | tr -cs 'A-Za-z0-9_.-' '_'
}

runner_out_dir() { printf '%s\n' "${RUNNER_OUT_DIR:-$RUNNER_ROOT/out}"; }
runner_runs_dir() { printf '%s\n' "$(runner_out_dir)/runs"; }
runner_state_dir() { printf '%s\n' "$(runner_out_dir)/state"; }

runner_prepare_out_dir() {
    local out
    out="$(runner_out_dir)"
    mkdir -p "$out"
    printf 'generic-dv-runner\nproject=%s\n' "${DV_PROJECT_NAME:-unconfigured}" > "$out/.dv_runner_root"
}

runner_update_latest_run() {
    local run_id="$1" kind="${2:-run}" state
    state="$(runner_state_dir)"
    mkdir -p "$state"
    printf '%s\n' "$run_id" > "$state/latest_run.txt"
    printf '%s\n' "$run_id" > "$state/latest_${kind}.txt"
}

runner_command_string() {
    local item output=''
    for item in "$@"; do
        printf -v item '%q' "$item"
        output+="${output:+ }$item"
    done
    printf '%s\n' "$output"
}

runner_write_command_file() {
    local file="$1"
    shift
    mkdir -p "$(dirname "$file")"
    {
        printf '#!/usr/bin/env bash\n'
        printf '# Generated by generic-dv-runner at %s\n' "$(date -Is)"
        runner_command_string "$@"
    } > "$file"
    chmod +x "$file" 2>/dev/null || true
}

runner_strip_ansi_log() {
    local source="$1" target="${2:-${1%.log}.clean.log}"
    [[ -f "$source" ]] || return 0
    LC_ALL=C sed -E $'s/\\x1B\\[[0-9;?]*[ -\\/]*[@-~]//g; s/\\r$//' "$source" > "$target" 2>/dev/null || cp -f "$source" "$target"
}

runner_sanitize_log_in_place() {
    local log_file="$1" temporary
    [[ -f "$log_file" ]] || return 0
    temporary="${log_file}.ansi_tmp.$$"
    if runner_strip_ansi_log "$log_file" "$temporary"; then
        mv -f -- "$temporary" "$log_file"
    else
        rm -f -- "$temporary"
        return 1
    fi
}

runner_log_for_analysis() {
    local file="$1" clean_file
    if [[ "$file" == *.log ]]; then
        clean_file="${file%.log}.clean.log"
        [[ -f "$clean_file" ]] && { printf '%s\n' "$clean_file"; return; }
    fi
    printf '%s\n' "$file"
}

runner_filelist_stats() {
    local file="$1" entries=0 bytes=0
    if [[ -r "$file" ]]; then
        entries="$(awk '!/^[[:space:]]*(#|$)/ {n++} END {print n+0}' "$file")"
        bytes="$(wc -c < "$file" | tr -d '[:space:]')"
    fi
    printf '%s|%s\n' "$entries" "$bytes"
}

runner_require_managed_out_dir() {
    local out
    out="$(runner_out_dir)"
    [[ -f "$out/.dv_runner_root" ]] || {
        runner_die "Output sentinel is missing; refusing destructive operation: $out"
        return $?
    }
}

runner_make_value() {
    local name="$1"
    "$RUNNER_SCRIPT_DIR/runner_make.sh" -s "$name" 2>/dev/null
}

runner_require_uint() {
    local label="$1" value="$2"
    [[ "$value" =~ ^[0-9]+$ ]] || runner_die "$label must be a non-negative integer: $value"
}

runner_normalize_dump_format() {
    local value="${1,,}"
    case "$value" in
        none|vcd|vpd|fsdb) printf '%s\n' "$value" ;;
        *) runner_die "Unsupported dump format: $1" ;;
    esac
}

runner_split_csv() {
    local value="$1"
    value="${value// /}"
    IFS=',' read -r -a RUNNER_SPLIT_RESULT <<< "$value"
}

runner_tail_failure() {
    local log_file="$1"
    [[ -f "$log_file" ]] || return 0
    runner_error "Last 40 log lines from $log_file"
    tail -n 40 "$log_file" >&2
}

runner_random_seeds() {
    local count="$1" i value
    RUNNER_RANDOM_SEEDS=()
    for ((i=0; i<count; i++)); do
        value=$(( (RANDOM << 16 | RANDOM) & 2147483647 ))
        ((value > 0)) || value=$((i + 1))
        RUNNER_RANDOM_SEEDS+=("$value")
    done
}

runner_auto_jobs() {
    local cap="${AUTO_PARALLEL_MAX_JOBS:-8}" detected=1
    if command -v nproc >/dev/null 2>&1; then detected="$(nproc)"; fi
    ((detected > cap)) && detected="$cap"
    ((detected > 0)) || detected=1
    printf '%s\n' "$detected"
}
