#!/usr/bin/env bash

# Persistent local I3C source selection and reviewed pin management.
# This script never fetches, checks out, resets, or edits either source tree.

runner_i3c_source_usage() {
    cat <<'EOF'
I3C Source Management

Usage:
  ./run.sh source set <I3C_ROOT> [--caliptra <CALIPTRA_ROOT>]
  ./run.sh source mode pinned|latest|worktree|snapshot
  ./run.sh source show
  ./run.sh source pin <I3C_COMMIT> [--root <I3C_ROOT>] [--dry-run]
  ./run.sh source pin --from <I3C_ROOT> [--caliptra <CALIPTRA_ROOT>] [--dry-run]
  ./run.sh source reset

Local commands manage an ignored configuration file. The pin command updates
the tracked reviewed-baseline manifest and should be committed through review.
No command modifies RTL or performs Git fetch, pull, checkout, or reset.
EOF
}

runner_i3c_source_abs_dir() {
    local path="$1"
    [[ -d "$path" ]] || { echo "[ERROR] Directory not found: $path" >&2; return 1; }
    (cd "$path" 2>/dev/null && pwd -P)
}

runner_i3c_source_git() {
    local repo="$1"
    shift
    git -c "safe.directory=$repo" -C "$repo" "$@"
}

runner_i3c_source_read_local() {
    I3C_LOCAL_ROOT_DIR=''
    I3C_LOCAL_CALIPTRA_ROOT=''
    I3C_LOCAL_SOURCE_MODE=''
    if [[ -r "$I3C_SOURCE_LOCAL_CONFIG" ]]; then
        # Generated by this script and contains assignments only.
        # shellcheck source=/dev/null
        source "$I3C_SOURCE_LOCAL_CONFIG"
    fi
}

runner_i3c_source_write_local() {
    local root="$1" caliptra="$2" mode="$3" dir tmp
    dir="$(dirname "$I3C_SOURCE_LOCAL_CONFIG")"
    mkdir -p "$dir"
    tmp="$(mktemp "$dir/.i3c_source.local.XXXXXX")" || return 1
    {
        echo '# Generated by ./run.sh source; local machine configuration.'
        [[ -z "$root" ]] || printf 'I3C_LOCAL_ROOT_DIR=%q\n' "$root"
        [[ -z "$caliptra" ]] || printf 'I3C_LOCAL_CALIPTRA_ROOT=%q\n' "$caliptra"
        [[ -z "$mode" ]] || printf 'I3C_LOCAL_SOURCE_MODE=%q\n' "$mode"
    } > "$tmp"
    mv -f "$tmp" "$I3C_SOURCE_LOCAL_CONFIG"
}

runner_i3c_source_set() {
    local root='' caliptra='' mode
    (($# > 0)) || { echo "[ERROR] source set requires an I3C checkout path" >&2; return 2; }
    root="$1"
    shift
    while (($#)); do
        case "$1" in
            --caliptra) [[ $# -ge 2 ]] || { echo "[ERROR] --caliptra requires a path" >&2; return 2; }; caliptra="$2"; shift 2 ;;
            *) echo "[ERROR] Unknown source set option: $1" >&2; return 2 ;;
        esac
    done
    root="$(runner_i3c_source_abs_dir "$root")" || return $?
    [[ -f "$root/src/i3c.f" ]] || { echo "[ERROR] Missing I3C filelist: $root/src/i3c.f" >&2; return 1; }
    [[ -n "$caliptra" ]] || caliptra="$root/third_party/caliptra-rtl"
    caliptra="$(runner_i3c_source_abs_dir "$caliptra")" || return $?
    [[ -f "$caliptra/src/caliptra_prim/rtl/caliptra_prim_pkg.sv" ]] || {
        echo "[ERROR] Missing Caliptra RTL under: $caliptra" >&2
        return 1
    }
    runner_i3c_source_read_local
    mode="$I3C_LOCAL_SOURCE_MODE"
    runner_i3c_source_write_local "$root" "$caliptra" "$mode" || return $?
    echo "[INFO] Saved local I3C source: $root"
    echo "[INFO] Saved local Caliptra source: $caliptra"
    echo "[NOTE] Run './run.sh source mode worktree' for active RTL development."
}

runner_i3c_source_mode() {
    local mode="${1:-}" root caliptra
    [[ $# -eq 1 ]] || { echo "[ERROR] Usage: ./run.sh source mode pinned|latest|worktree|snapshot" >&2; return 2; }
    case "$mode" in pinned|latest|worktree|snapshot) ;; *) echo "[ERROR] Invalid source mode: $mode" >&2; return 2 ;; esac
    runner_i3c_source_read_local
    root="$I3C_LOCAL_ROOT_DIR"
    caliptra="$I3C_LOCAL_CALIPTRA_ROOT"
    runner_i3c_source_write_local "$root" "$caliptra" "$mode" || return $?
    echo "[INFO] Saved local source mode: $mode"
    [[ "$mode" != pinned ]] || echo "[NOTE] Pinned mode rejects commit mismatches and dirty sources."
}

runner_i3c_source_load_pins() {
    [[ -r "$I3C_SOURCE_PIN_MANIFEST" ]] || { echo "[ERROR] Pin manifest not found: $I3C_SOURCE_PIN_MANIFEST" >&2; return 1; }
    # shellcheck source=/dev/null
    source "$I3C_SOURCE_PIN_MANIFEST"
}

runner_i3c_source_show() {
    local root caliptra mode i3c_head='N/A' caliptra_head='N/A' status='UNAVAILABLE'
    runner_i3c_source_read_local
    runner_i3c_source_load_pins || return $?
    root="${I3C_LOCAL_ROOT_DIR:-${I3C_ROOT_DIR:-}}"
    caliptra="${I3C_LOCAL_CALIPTRA_ROOT:-${CALIPTRA_ROOT:-${root:+$root/third_party/caliptra-rtl}}}"
    mode="${I3C_LOCAL_SOURCE_MODE:-${SOURCE_MODE:-pinned}}"
    [[ ! -d "$root" ]] || i3c_head="$(runner_i3c_source_git "$root" rev-parse HEAD 2>/dev/null || echo N/A)"
    [[ ! -d "$caliptra" ]] || caliptra_head="$(runner_i3c_source_git "$caliptra" rev-parse HEAD 2>/dev/null || echo N/A)"
    if [[ "$i3c_head" != N/A && "$caliptra_head" != N/A ]]; then
        if [[ "$i3c_head" == "$I3C_EXPECTED_COMMIT" && "$caliptra_head" == "$CALIPTRA_EXPECTED_COMMIT" ]]; then
            status='MATCHED'
        elif [[ "$mode" == worktree ]]; then
            status='DIFFERS_FROM_PIN_ACCEPTED'
        else
            status='DIFFERS_FROM_PIN'
        fi
    fi
    printf '%-20s %s\n' \
        'Local config' "$I3C_SOURCE_LOCAL_CONFIG" \
        'Config exists' "$([[ -r "$I3C_SOURCE_LOCAL_CONFIG" ]] && echo yes || echo no)" \
        'I3C source' "${root:-(not set)}" \
        'I3C HEAD' "$i3c_head" \
        'Pinned I3C' "$I3C_EXPECTED_COMMIT" \
        'Caliptra source' "${caliptra:-(not set)}" \
        'Caliptra HEAD' "$caliptra_head" \
        'Pinned Caliptra' "$CALIPTRA_EXPECTED_COMMIT" \
        'Expected branch' "$I3C_EXPECTED_BRANCH" \
        'Source mode' "$mode" \
        'Status' "$status"
}

runner_i3c_source_update_manifest() {
    local i3c_commit="$1" caliptra_commit="$2" dry_run="$3" old_i3c old_caliptra dir tmp
    runner_i3c_source_load_pins || return $?
    old_i3c="$I3C_EXPECTED_COMMIT"
    old_caliptra="$CALIPTRA_EXPECTED_COMMIT"
    printf '%-20s %s -> %s\n' 'I3C pin' "$old_i3c" "$i3c_commit"
    printf '%-20s %s -> %s\n' 'Caliptra pin' "$old_caliptra" "$caliptra_commit"
    [[ "$dry_run" == 0 ]] || { echo "[INFO] Dry run: pin manifest was not modified."; return 0; }
    dir="$(dirname "$I3C_SOURCE_PIN_MANIFEST")"
    tmp="$(mktemp "$dir/.i3c_source_pins.XXXXXX")" || return 1
    awk -v i3c="$i3c_commit" -v caliptra="$caliptra_commit" '
        /^I3C_EXPECTED_COMMIT=/ {print "I3C_EXPECTED_COMMIT=" i3c; next}
        /^CALIPTRA_EXPECTED_COMMIT=/ {print "CALIPTRA_EXPECTED_COMMIT=" caliptra; next}
        {print}
    ' "$I3C_SOURCE_PIN_MANIFEST" > "$tmp"
    mv -f "$tmp" "$I3C_SOURCE_PIN_MANIFEST"
    echo "[INFO] Updated reviewed pin manifest: $I3C_SOURCE_PIN_MANIFEST"
    echo "[NOTE] Review and commit this tracked baseline change."
}

runner_i3c_source_pin() {
    local requested='' root='' caliptra='' from=0 dry_run=0 i3c_commit caliptra_commit gitlink
    while (($#)); do
        case "$1" in
            --from) [[ $# -ge 2 ]] || { echo "[ERROR] --from requires an I3C checkout" >&2; return 2; }; root="$2"; from=1; shift 2 ;;
            --root) [[ $# -ge 2 ]] || { echo "[ERROR] --root requires an I3C checkout" >&2; return 2; }; root="$2"; shift 2 ;;
            --caliptra) [[ $# -ge 2 ]] || { echo "[ERROR] --caliptra requires a checkout" >&2; return 2; }; caliptra="$2"; shift 2 ;;
            --dry-run) dry_run=1; shift ;;
            -*) echo "[ERROR] Unknown source pin option: $1" >&2; return 2 ;;
            *) [[ -z "$requested" ]] || { echo "[ERROR] Only one I3C commit may be specified" >&2; return 2; }; requested="$1"; shift ;;
        esac
    done
    if ((from)) && [[ -n "$requested" ]]; then echo "[ERROR] Use either --from or an explicit commit, not both" >&2; return 2; fi
    if ((!from)) && [[ -z "$requested" ]]; then echo "[ERROR] source pin requires <I3C_COMMIT> or --from <I3C_ROOT>" >&2; return 2; fi
    runner_i3c_source_read_local
    root="${root:-${I3C_LOCAL_ROOT_DIR:-${I3C_ROOT_DIR:-}}}"
    [[ -n "$root" ]] || { echo "[ERROR] I3C source is not configured; use './run.sh source set <path>'" >&2; return 2; }
    root="$(runner_i3c_source_abs_dir "$root")" || return $?
    runner_i3c_source_git "$root" rev-parse --git-dir >/dev/null 2>&1 || { echo "[ERROR] I3C source is not a Git worktree: $root" >&2; return 1; }
    if ((from)); then
        i3c_commit="$(runner_i3c_source_git "$root" rev-parse 'HEAD^{commit}' 2>/dev/null)" || { echo "[ERROR] Cannot resolve I3C HEAD" >&2; return 1; }
        caliptra="${caliptra:-${I3C_LOCAL_CALIPTRA_ROOT:-${CALIPTRA_ROOT:-$root/third_party/caliptra-rtl}}}"
        caliptra="$(runner_i3c_source_abs_dir "$caliptra")" || return $?
        caliptra_commit="$(runner_i3c_source_git "$caliptra" rev-parse 'HEAD^{commit}' 2>/dev/null)" || { echo "[ERROR] Cannot resolve Caliptra HEAD" >&2; return 1; }
        gitlink="$(runner_i3c_source_git "$root" rev-parse "$i3c_commit:third_party/caliptra-rtl" 2>/dev/null || true)"
        if [[ -n "$gitlink" && "$caliptra_commit" != "$gitlink" ]]; then
            echo "[WARNING] Caliptra HEAD does not match the I3C commit gitlink." >&2
            echo "[WARNING] Gitlink : $gitlink" >&2
            echo "[WARNING] Checkout: $caliptra_commit" >&2
            echo "[NOTE] Prefer './run.sh source pin $i3c_commit' to pin the coherent gitlink pair." >&2
        fi
    else
        i3c_commit="$(runner_i3c_source_git "$root" rev-parse "$requested^{commit}" 2>/dev/null)" || {
            echo "[ERROR] I3C commit is not available in the local checkout: $requested" >&2
            echo "[NOTE] This command does not fetch; make the commit available first." >&2
            return 1
        }
        caliptra_commit="$(runner_i3c_source_git "$root" rev-parse "$i3c_commit:third_party/caliptra-rtl" 2>/dev/null)" || {
            echo "[ERROR] Commit does not contain third_party/caliptra-rtl gitlink: $i3c_commit" >&2
            return 1
        }
    fi
    runner_i3c_source_update_manifest "$i3c_commit" "$caliptra_commit" "$dry_run"
}

runner_i3c_source_reset() {
    if [[ -e "$I3C_SOURCE_LOCAL_CONFIG" ]]; then
        rm -f "$I3C_SOURCE_LOCAL_CONFIG"
        echo "[INFO] Removed local I3C source configuration: $I3C_SOURCE_LOCAL_CONFIG"
    else
        echo "[INFO] Local I3C source configuration is already absent."
    fi
    echo "[NOTE] Project defaults will be used on the next run."
}

runner_manage_i3c_source() {
    local action="${1:-show}"
    (($# == 0)) || shift
    case "$action" in
        set) runner_i3c_source_set "$@" ;;
        mode) runner_i3c_source_mode "$@" ;;
        show) [[ $# -eq 0 ]] || { echo "[ERROR] source show accepts no options" >&2; return 2; }; runner_i3c_source_show ;;
        pin) runner_i3c_source_pin "$@" ;;
        reset) [[ $# -eq 0 ]] || { echo "[ERROR] source reset accepts no options" >&2; return 2; }; runner_i3c_source_reset ;;
        help|-h|--help) runner_i3c_source_usage ;;
        *) echo "[ERROR] Unknown source action: $action" >&2; runner_i3c_source_usage >&2; return 2 ;;
    esac
}
