# Auto-generated by sim/scripts/gen_mk_files.sh
# Starter regression test list regenerated from i3c/verify/tb/tests
# Format:
# BURST_LIMITS light=50 medium=20 heavy=10 extra=1
# BURST_PLAN light=seed-major medium=seed-major heavy=seed-major extra=seed-major
# Supported burst plan values: seed-major, packed, test-major
#   seed-major = finish all selected tests for one seed before the next seed
#   packed     = planner may group multiple tests/seeds in one burst for throughput
#   test-major = finish one test across its seed chunks before the next test
# Regression group format:
#   <label> : <level> <on/off> {
#   test_name
#   test_name | case_id | +PLUSARG=value [+FLAG]
# }
# label must be unique. level accepts light, medium/med, heavy/high, extra.
# off groups are skipped by --all and level selection.
# Prefix an individual test with # to disable it without auto-rediscovery.
# Metadata comments are parsed; other comment lines are ignored.
# Per-test compile requirement syntax is TEST_REQUIRES_COMPILE followed by
# <test_name>=<requirement>[,<requirement>...].
# Requirements are simulator-neutral; the runner maps them to backend options.
# TEST_REQUIRES_COMPILE smc_i3c_ibi_target_tx_overflow_test=hdl_access

i3c_smoke : light on {
smc_i3c_csr_smoke_test
smc_i3c_sanity_test
}

i3c_ral : heavy on {
smc_i3c_ral_all_regs_test
}

# Coverage-ready IBI tests. The normalized plan adds +IBI_REQUIRE_COV, and
# only their latest-PASS VDBs contribute to --all coverage runs.
i3c_ibi_coverage : medium on {
smc_i3c_ibi_target_tx_basic_test
smc_i3c_ibi_target_tx_ack_nack_test
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_one_payload | +IBI_RETRY_COUNT=1 +IBI_RETRY_PAYLOAD_LEN=1
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_one_none | +IBI_RETRY_COUNT=1 +IBI_RETRY_PAYLOAD_LEN=0
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_one_short | +IBI_RETRY_COUNT=1 +IBI_RETRY_PAYLOAD_LEN=3
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_one_medium | +IBI_RETRY_COUNT=1 +IBI_RETRY_PAYLOAD_LEN=6
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_one_long | +IBI_RETRY_COUNT=1 +IBI_RETRY_PAYLOAD_LEN=10
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_few_short | +IBI_RETRY_COUNT=2 +IBI_RETRY_PAYLOAD_LEN=3
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_few_medium | +IBI_RETRY_COUNT=3 +IBI_RETRY_PAYLOAD_LEN=6
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_few_none | +IBI_RETRY_COUNT=2 +IBI_RETRY_PAYLOAD_LEN=0
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_few_one | +IBI_RETRY_COUNT=2 +IBI_RETRY_PAYLOAD_LEN=1
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_few_long | +IBI_RETRY_COUNT=3 +IBI_RETRY_PAYLOAD_LEN=10
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_many_long | +IBI_RETRY_COUNT=6 +IBI_RETRY_PAYLOAD_LEN=10
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_many_none | +IBI_RETRY_COUNT=4 +IBI_RETRY_PAYLOAD_LEN=0
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_many_one | +IBI_RETRY_COUNT=4 +IBI_RETRY_PAYLOAD_LEN=1
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_many_short | +IBI_RETRY_COUNT=4 +IBI_RETRY_PAYLOAD_LEN=3
smc_i3c_ibi_target_tx_retry_arbitration_test | retry_many_medium | +IBI_RETRY_COUNT=4 +IBI_RETRY_PAYLOAD_LEN=6
smc_i3c_ibi_target_tx_retry_exhaustion_test | retry_exhaust_few | +IBI_RETRY_COUNT=2 +IBI_RETRY_PAYLOAD_LEN=0
smc_i3c_ibi_target_tx_multi_target_test
smc_i3c_ibi_target_tx_dut_loss_test
smc_i3c_ibi_target_tx_dut_loss_test | dut_loss_failure_addr_arb_correlation | +IBI_CORRELATE_FAILURE_ADDR_ARB=1
smc_i3c_ibi_target_tx_dut_loss_test | dut_loss_bus_start_context | +IBI_DUT_ARB_CONTEXT=bus_start +IBI_CORRELATE_FAILURE_ADDR_ARB=1
smc_i3c_ibi_target_tx_dut_loss_test | dut_loss_after_transfer_then_arbitration | +IBI_ARB_PRECEDE_PRIVATE_WRITE=1 +IBI_CORRELATE_FAILURE_ADDR_ARB=1
smc_i3c_ibi_target_tx_dut_loss_test | dut_loss_contested_after_transfer | +IBI_ARB_DURING_PRIVATE_WRITE=1 +IBI_CORRELATE_FAILURE_ADDR_ARB=1
smc_i3c_ibi_target_tx_dut_loss_test | dut_loss_three_requesters | +IBI_DUT_LOSS_REQUESTERS=3
smc_i3c_ibi_target_tx_dut_loss_test | dut_loss_four_requesters | +IBI_DUT_LOSS_REQUESTERS=4
smc_i3c_ibi_target_tx_dut_win_test
smc_i3c_ibi_target_tx_dut_win_test | dut_win_after_transfer_then_arbitration | +IBI_ARB_PRECEDE_PRIVATE_WRITE=1
smc_i3c_ibi_target_tx_dut_win_test | dut_win_contested_after_transfer | +IBI_ARB_DURING_PRIVATE_WRITE=1
smc_i3c_ibi_target_tx_dut_win_test | dut_win_nack_retry | +IBI_DUT_WIN_NACK_RETRY=1
smc_i3c_ibi_target_tx_mdb_payload_test
smc_i3c_ibi_target_tx_partial_recovery_test
smc_i3c_ibi_target_tx_fifo_irq_test
smc_i3c_ibi_controller_rx_basic_test
smc_i3c_ibi_controller_rx_content_test | content_mdb_only | +IBI_CONTENT_PAYLOAD_LEN=0
smc_i3c_ibi_controller_rx_content_test | content_one_byte | +IBI_CONTENT_PAYLOAD_LEN=1
smc_i3c_ibi_controller_rx_content_test | content_non_dword | +IBI_CONTENT_PAYLOAD_LEN=3
smc_i3c_ibi_controller_rx_content_test | content_dword_boundary | +IBI_CONTENT_PAYLOAD_LEN=4
smc_i3c_ibi_controller_rx_content_test | content_multi_dword | +IBI_CONTENT_PAYLOAD_LEN=7
smc_i3c_ibi_controller_rx_content_test | content_long | +IBI_CONTENT_PAYLOAD_LEN=10
smc_i3c_ibi_controller_rx_timing_context_test | timing_idle | +IBI_TIMING_CONTEXT=idle
smc_i3c_ibi_controller_rx_timing_context_test | timing_after_xfer | +IBI_TIMING_CONTEXT=after_xfer
smc_i3c_ibi_controller_rx_timing_context_test | timing_busy_defer | +IBI_TIMING_CONTEXT=busy_defer
smc_i3c_ibi_target_tx_busy_bus_block_test
smc_i3c_ibi_controller_rx_policy_test | policy_dat_accept | +IBI_POLICY_CASE=1
smc_i3c_ibi_controller_rx_policy_test | policy_dat_reject | +IBI_POLICY_CASE=2
smc_i3c_ibi_controller_rx_policy_test | policy_payload_disabled | +IBI_POLICY_CASE=3
}

# Separate DUT-Controller/two-UVM-Target scenario; it is not an alias of the
# DUT-Target test.
i3c_ibi_legacy_aliases : light on {
smc_i3c_ibi_controller_rx_multi_target_test
}

# Work in progress. Tests that produce a functional IBI event receive
# +IBI_REQUIRE_COV from the generated plan. Reset-flush and invalid-target
# negative scenarios are explicit coverage-sample exceptions because their
# legal PASS path may intentionally produce no accepted IBI event.
# These tests are specification-facing and
# should PASS on a conforming DUT, but have not yet completed a clean simulation
# run. The pending-read test follows the advertised HCI Auto-Command capability
# and always completes the required Private Read contract.
i3c_ibi_wip : light on {
smc_i3c_ibi_controller_rx_reset_flush_test
smc_i3c_ibi_target_tx_recovery_cleanup_test
smc_i3c_ibi_controller_rx_recovery_cleanup_test
smc_i3c_ibi_controller_rx_mdb_decode_test
smc_i3c_ibi_controller_rx_pending_read_notification_test
# Overflow closure uses separate test identities so regression and coverage
# results cannot accidentally close the opposite DUT role.
smc_i3c_ibi_target_tx_overflow_test
smc_i3c_ibi_controller_rx_overflow_test
}

# Coverage-directed random scenarios. The generated testplan assigns multiple
# default seeds and the random-seed tag only to this group; directed tests
# remain at seed 1. Explicit --seeds overrides every selected entry, while
# --rand-num only replaces seeds for this tagged group. Controller random runs
# one IBI per seed due the current Controller re-entry defect.
i3c_ibi_random : medium on {
smc_i3c_ibi_target_tx_random_test | closure_24 | +IBI_RANDOM_ITERS=24 +IBI_RANDOM_MUST_HIT=1
smc_i3c_ibi_target_tx_stress_test | ack_burst_100 | +IBI_RANDOM_ITERS=100 +IBI_STRESS_PROFILE=ack_burst
smc_i3c_ibi_target_tx_stress_test | mixed_response_60 | +IBI_RANDOM_ITERS=60 +IBI_STRESS_PROFILE=mixed_response +IBI_RANDOM_MUST_HIT=1
smc_i3c_ibi_controller_rx_random_test | policy_seed_sweep
}

# Multi-target sign-off is split by verification intent so each family can be
# run and triaged independently. These tests use two to four configured Target
# slots and the generated plan requires IBI coverage samples. The Controller-RX
# base multi-target scenario now exercises all four active requesters.
i3c_ibi_multi_target_arbitration : heavy on {
smc_i3c_ibi_target_tx_multi_target_addr_matrix_test
smc_i3c_ibi_target_tx_multi_target_retry_limit_test
}

i3c_ibi_multi_target_content_timing : heavy on {
smc_i3c_ibi_target_tx_multi_target_timing_test
smc_i3c_ibi_target_tx_multi_target_content_test
}

i3c_ibi_multi_target_controller : heavy on {
smc_i3c_ibi_controller_rx_multi_target_ordering_test
smc_i3c_ibi_controller_rx_multi_target_ack_nack_test
smc_i3c_ibi_controller_rx_multi_target_queue_pressure_test
}

# RTL does not implement the HCI SOFT_RST self-clear behavior. Keep this
# and the positive no-MDB Controller reproduction out of ordinary regression
# selection until their RTL/design contracts are resolved.
i3c_ibi_rtl_unsupported : heavy off {
smc_i3c_ibi_controller_rx_soft_rst_selfclear_test
smc_i3c_ibi_controller_rx_no_mdb_test
}

# Contract-backed Target runtime eligibility negatives: no valid Dynamic
# Address and IBI_EN clear. This supported test is part of ordinary regression.
i3c_ibi_runtime_negative : heavy on {
smc_i3c_ibi_target_tx_invalid_target_test
}

# Focused risk cases validated on the pinned RTL revision. FIFO IRQ and DAT
# no-match pass their scoreboards and SVA; multi-target recovery passes after
# controller-pad role selection and passive recovery-checker construction.
i3c_ibi_validated_rechecks : heavy on {
smc_i3c_ibi_controller_rx_fifo_irq_test
smc_i3c_ibi_controller_rx_policy_test | policy_dat_no_match | +IBI_POLICY_CASE=4
smc_i3c_ibi_multi_target_recovery_test | | +IBI_REQUIRE_COV +IBI_DUT_CONTROLLER=1
}
