# Auto-generated by sim/vcs_run_script/gen_mk_files.sh
# *****************************************************************************
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 VNCHIP LABS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# File        : test.f
# Description : TT UVM I3C simulation support file.
# Authors     : Duy Huynh, Dang Thai
# Date        : 2026-08-11
#
# *****************************************************************************

# Starter regression test list regenerated from i3c/verify/tb/tests
# Format:
# BURST_LIMITS light=50 medium=20 heavy=10 extra=1
# BURST_PLAN light=seed-major medium=seed-major heavy=seed-major extra=seed-major
# Supported burst plan values: seed-major, packed, test-major
#   seed-major = finish all selected tests for one seed before the next seed
#   packed     = planner may group multiple tests/seeds in one burst for throughput
#   test-major = finish one test across its seed chunks before the next test
# Regression group format:
#   <label> : <level> <on/off> {
#   test_name
# }
# label must be unique. level accepts light, medium/med, heavy/high, extra.
# off groups are skipped by --all and level selection.
# Metadata comments are parsed; other comment lines are ignored.

i3c_smoke : light on {
smc_i3c_csr_smoke_test
smc_i3c_sanity_test
}

i3c_ral : heavy on {
smc_i3c_ral_all_regs_test
}

# Coverage-ready IBI tests. The normalized plan adds +IBI_REQUIRE_COV, and
# only their latest-PASS VDBs contribute to --all coverage runs.
i3c_ibi_coverage : medium on {
smc_i3c_ibi_basic_test
smc_i3c_ibi_ack_nack_test
smc_i3c_ibi_mdb_payload_test
smc_i3c_ibi_fifo_irq_test
smc_i3c_ibi_controller_receive_test
smc_i3c_ibi_controller_content_test
smc_i3c_ibi_controller_timing_context_test
}

# RTL defect-reproduction tests. Keep failures visible in regression results;
# failed VDB inclusion remains an explicit merge-time decision.
i3c_ibi_rtl_defects : light on {
smc_i3c_ibi_controller_policy_test
smc_i3c_ibi_controller_multi_target_test
}
