# *****************************************************************************
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 VNCHIP LABS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# File        : incdirs.mk
# Description : Auto-generated include-directory makefile fragment.
# Authors     : Duy Huynh, Dang Thai
# Date        : 2026-08-11
#
# *****************************************************************************

# Auto-generated by sim/vcs_run_script/gen_mk_files.sh

INCDIRS := \
    +incdir+$(ROOT_DIR)/rtl \
    +incdir+$(ROOT_DIR)/verify/vip/axi4lite_vip \
    +incdir+$(ROOT_DIR)/verify/vip/i3c_vip \
    +incdir+$(ROOT_DIR)/verify/vip/smc_peripherals_vip \
    +incdir+$(ROOT_DIR)/verify/vip/axi4lite_vip/agent \
    +incdir+$(ROOT_DIR)/verify/vip/axi4lite_vip/core \
    +incdir+$(ROOT_DIR)/verify/vip/axi4lite_vip/if \
    +incdir+$(ROOT_DIR)/verify/vip/axi4lite_vip/sequences \
    +incdir+$(ROOT_DIR)/verify/vip/i3c_vip/agent \
    +incdir+$(ROOT_DIR)/verify/vip/i3c_vip/core \
    +incdir+$(ROOT_DIR)/verify/vip/i3c_vip/if \
    +incdir+$(ROOT_DIR)/verify/vip/i3c_vip/sequences \
    +incdir+$(ROOT_DIR)/verify/vip/smc_peripherals_vip/if \
    +incdir+$(ROOT_DIR)/verify/tb/ral \
    +incdir+$(ROOT_DIR)/verify/tb/coverage \
    +incdir+$(ROOT_DIR)/verify/tb/env \
    +incdir+$(ROOT_DIR)/verify/tb/sequences \
    +incdir+$(ROOT_DIR)/verify/tb/tests \
    +incdir+$(ROOT_DIR)/verify/tb/top \
    +incdir+$(ROOT_DIR)/verify/tb/sva \
    +incdir+$(ROOT_DIR)/verify/tb/vseq \
    +incdir+$(ROOT_DIR)/verify/tb/env/analysis \
    +incdir+$(ROOT_DIR)/verify/tb/env/core \
    +incdir+$(ROOT_DIR)/verify/tb/env/helpers \
    +incdir+$(ROOT_DIR)/verify/tb/env/ip \
    +incdir+$(ROOT_DIR)/verify/tb/env/services \
    +incdir+$(ROOT_DIR)/verify/tb/coverage/checker \
    +incdir+$(ROOT_DIR)/verify/tb/coverage/integration \
    +incdir+$(ROOT_DIR)/verify/tb/coverage/internal \
    +incdir+$(ROOT_DIR)/verify/tb/coverage/ip \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/core \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/core/base \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/ip_only \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/ip_only/i3c \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/ip_only/i3c/ibi \
    +incdir+$(ROOT_DIR)/verify/tb/tests/core \
    +incdir+$(ROOT_DIR)/verify/tb/tests/core/base \
    +incdir+$(ROOT_DIR)/verify/tb/tests/ip_only \
    +incdir+$(ROOT_DIR)/verify/tb/tests/ip_only/i3c \
    +incdir+$(ROOT_DIR)/verify/tb/tests/ip_only/i3c/ibi \
    +incdir+$(ROOT_DIR)/verify/tb/sequences/ral \
    +incdir+$(ROOT_DIR)/verify/tb/sequences/seq \
    +incdir+$(ROOT_DIR)/verify/tb/sequences/seq/csr \
    +incdir+$(ROOT_DIR)/verify/tb/sva/bind \
    +incdir+$(ROOT_DIR)/verify/tb/sva/common \
    +incdir+$(ROOT_DIR)/verify/tb/sva/integration \
    +incdir+$(ROOT_DIR)/verify/tb/sva/ip \
    +incdir+$(ROOT_DIR)/verify/tb/sva/waivers \
    +incdir+$(ROOT_DIR)/verify/tb/sva/waivers/policies
