# Auto-generated by sim/scripts/gen_mk_files.sh

INCDIRS := \
    +incdir+$(ROOT_DIR)/rtl \
    +incdir+$(ROOT_DIR)/verify/vip/axi4lite_vip \
    +incdir+$(ROOT_DIR)/verify/vip/i3c_vip \
    +incdir+$(ROOT_DIR)/verify/vip/axi4lite_vip/agent \
    +incdir+$(ROOT_DIR)/verify/vip/axi4lite_vip/core \
    +incdir+$(ROOT_DIR)/verify/vip/axi4lite_vip/if \
    +incdir+$(ROOT_DIR)/verify/vip/axi4lite_vip/sequences \
    +incdir+$(ROOT_DIR)/verify/vip/i3c_vip/agent \
    +incdir+$(ROOT_DIR)/verify/vip/i3c_vip/core \
    +incdir+$(ROOT_DIR)/verify/vip/i3c_vip/if \
    +incdir+$(ROOT_DIR)/verify/vip/i3c_vip/sequences \
    +incdir+$(ROOT_DIR)/verify/tb/ral \
    +incdir+$(ROOT_DIR)/verify/tb/coverage \
    +incdir+$(ROOT_DIR)/verify/tb/env \
    +incdir+$(ROOT_DIR)/verify/tb/interfaces \
    +incdir+$(ROOT_DIR)/verify/tb/sequences \
    +incdir+$(ROOT_DIR)/verify/tb/tests \
    +incdir+$(ROOT_DIR)/verify/tb/top \
    +incdir+$(ROOT_DIR)/verify/tb/sva \
    +incdir+$(ROOT_DIR)/verify/tb/vseq \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/ip_only/i3c \
    +incdir+$(ROOT_DIR)/verify/tb/tests/ip_only/i3c \
    +incdir+$(ROOT_DIR)/verify/tb/env/analysis \
    +incdir+$(ROOT_DIR)/verify/tb/env/core \
    +incdir+$(ROOT_DIR)/verify/tb/env/helpers \
    +incdir+$(ROOT_DIR)/verify/tb/env/ip \
    +incdir+$(ROOT_DIR)/verify/tb/env/services \
    +incdir+$(ROOT_DIR)/verify/tb/coverage/integration \
    +incdir+$(ROOT_DIR)/verify/tb/coverage/internal \
    +incdir+$(ROOT_DIR)/verify/tb/coverage/ip \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/core/base \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/ip_only/i3c/common \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/ip_only/i3c/config \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/ip_only/i3c/ibi/base \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/ip_only/i3c/ibi/controller_rx \
    +incdir+$(ROOT_DIR)/verify/tb/vseq/ip_only/i3c/ibi/target_tx \
    +incdir+$(ROOT_DIR)/verify/tb/tests/core/base \
    +incdir+$(ROOT_DIR)/verify/tb/tests/ip_only/i3c/common \
    +incdir+$(ROOT_DIR)/verify/tb/tests/ip_only/i3c/ibi/base \
    +incdir+$(ROOT_DIR)/verify/tb/tests/ip_only/i3c/ibi/controller_rx \
    +incdir+$(ROOT_DIR)/verify/tb/tests/ip_only/i3c/ibi/target_tx \
    +incdir+$(ROOT_DIR)/verify/tb/sequences/i3c/ibi \
    +incdir+$(ROOT_DIR)/verify/tb/sva/integration \
    +incdir+$(ROOT_DIR)/verify/tb/sva/waivers \
    +incdir+$(ROOT_DIR)/verify/tb/sva/waivers/policies
