# *****************************************************************************
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 VNCHIP LABS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# File        : paths.mk
# Description : Auto-generated simulation paths makefile fragment.
# Authors     : Duy Huynh, Dang Thai
# Date        : 2026-08-11
#
# *****************************************************************************

# Auto-generated by sim/vcs_run_script/gen_mk_files.sh

ROOT_DIR     := $(abspath $(SIM_MAKEFILE_DIR)/..)
SIM_DIR      := $(SIM_MAKEFILE_DIR)
SCRIPTS_DIR  := $(SIM_DIR)/vcs_run_script
RTL_DIR      := $(ROOT_DIR)/rtl
VERIFY_DIR   := $(ROOT_DIR)/verify
VIP_DIR      := $(VERIFY_DIR)/vip
TB_DIR       := $(VERIFY_DIR)/tb
CHECKERS_DIR := $(VERIFY_DIR)/checkers
LOG_DIR      := logs
FILELIST_DIR := $(SIM_DIR)/filelists
RTL_FLIST    := $(FILELIST_DIR)/rtl.f
TEST_FLIST   := $(FILELIST_DIR)/test.f
