# Auto-generated by sim/scripts/gen_mk_files.sh

ROOT_DIR     := $(abspath $(SIM_MAKEFILE_DIR)/..)
SIM_DIR      := $(SIM_MAKEFILE_DIR)
SCRIPTS_DIR  := $(SIM_DIR)/scripts
RTL_DIR      := $(ROOT_DIR)/rtl
VERIFY_DIR   := $(ROOT_DIR)/verify
VIP_DIR      := $(VERIFY_DIR)/vip
TB_DIR       := $(VERIFY_DIR)/tb
CHECKERS_DIR := $(VERIFY_DIR)/checkers
LOG_DIR      := logs
FILELIST_DIR := $(SIM_DIR)/filelists
RTL_FLIST    := $(FILELIST_DIR)/rtl.f
TEST_FLIST   := $(FILELIST_DIR)/test.f
