# Auto-generated by sim/scripts/gen_mk_files.sh

TB_CORE_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/top/i3c_tb_params_pkg.sv \
    $(ROOT_DIR)/verify/tb/top/i3c_report_pkg.sv

VIP_IF_SRC_FILES := \
    $(ROOT_DIR)/verify/vip/axi4lite_vip/if/axi4lite_if.sv \
    $(ROOT_DIR)/verify/tb/interfaces/i3c_tb_if.sv

TB_RAL_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/ral/i3c_ral_pkg.sv

VIP_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/vip/axi4lite_vip/axi4lite_vip_pkg.sv

CHECKER_PKG_SRC_FILES :=

TB_COV_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/coverage/i3c_coverage_pkg.sv

TB_ENV_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/env/i3c_env_pkg.sv

TB_VSEQ_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/vseq/i3c_vseq_pkg.sv

TB_TEST_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/tests/i3c_test_pkg.sv

ORDERED_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/vip/axi4lite_vip/axi4lite_vip_pkg.sv \
    $(ROOT_DIR)/verify/tb/coverage/i3c_coverage_pkg.sv \
    $(ROOT_DIR)/verify/tb/ral/i3c_ral_pkg.sv \
    $(ROOT_DIR)/verify/tb/env/i3c_env_pkg.sv \
    $(ROOT_DIR)/verify/tb/vseq/i3c_vseq_pkg.sv \
    $(ROOT_DIR)/verify/tb/tests/i3c_test_pkg.sv

SVA_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/sva/integration/i3c_ibi_bus_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/i3c_ibi_controller_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/i3c_ibi_protocol_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/i3c_ibi_target_sva.sv

TB_TOP_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/top/tb_i3c_top.sv

SRC_FILES := \
    $(TB_CORE_PKG_SRC_FILES) \
    $(VIP_IF_SRC_FILES) \
    $(ORDERED_PKG_SRC_FILES) \
    $(SVA_SRC_FILES) \
    $(TB_TOP_SRC_FILES)
