# *****************************************************************************
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 VNCHIP LABS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# File        : srcs.mk
# Description : Auto-generated source-list makefile fragment.
# Authors     : Duy Huynh, Dang Thai
# Date        : 2026-08-11
#
# *****************************************************************************

# Auto-generated by sim/vcs_run_script/gen_mk_files.sh

TB_CORE_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/top/smc_peripherals_tb_params_pkg.sv \
    $(ROOT_DIR)/verify/tb/top/smc_peripherals_report_pkg.sv

VIP_IF_SRC_FILES := \
    $(ROOT_DIR)/verify/vip/axi4lite_vip/if/axi4lite_if.sv \
    $(ROOT_DIR)/verify/vip/smc_peripherals_vip/if/smc_peripherals_if.sv

TB_RAL_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/ral/smc_peripherals_ral_pkg.sv

VIP_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/vip/axi4lite_vip/axi4lite_vip_pkg.sv

CHECKER_PKG_SRC_FILES :=

TB_COV_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/coverage/smc_i3c_coverage_pkg.sv

TB_ENV_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/env/smc_peripherals_env_pkg.sv

TB_VSEQ_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/vseq/smc_peripherals_vseq_pkg.sv

TB_TEST_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/tests/smc_peripherals_test_pkg.sv

ORDERED_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/vip/axi4lite_vip/axi4lite_vip_pkg.sv \
    $(ROOT_DIR)/verify/tb/coverage/smc_i3c_coverage_pkg.sv \
    $(ROOT_DIR)/verify/tb/ral/smc_peripherals_ral_pkg.sv \
    $(ROOT_DIR)/verify/tb/env/smc_peripherals_env_pkg.sv \
    $(ROOT_DIR)/verify/tb/vseq/smc_peripherals_vseq_pkg.sv \
    $(ROOT_DIR)/verify/tb/tests/smc_peripherals_test_pkg.sv

SVA_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/sva/integration/smc_i3c_boundary_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/smc_i3c_ibi_bus_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/smc_i3c_ibi_controller_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/smc_i3c_ibi_protocol_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/smc_i3c_ibi_target_sva.sv

TB_TOP_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/top/tb_smc_peripherals_top.sv

RTL_SRC_FILES := -f $(RTL_FLIST)

SRC_FILES := \
    $(TB_CORE_PKG_SRC_FILES) \
    $(VIP_IF_SRC_FILES) \
    $(ORDERED_PKG_SRC_FILES) \
    $(SVA_SRC_FILES) \
    $(TB_TOP_SRC_FILES) \
    $(RTL_SRC_FILES)
