# Auto-generated by sim/scripts/gen_mk_files.sh

TB_CORE_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/top/smc_peripherals_tb_params_pkg.sv \
    $(ROOT_DIR)/verify/tb/top/smc_peripherals_report_pkg.sv

VIP_IF_SRC_FILES := \
    $(ROOT_DIR)/verify/vip/axi4lite_vip/if/axi4lite_if.sv \
    $(ROOT_DIR)/verify/tb/interfaces/smc_peripherals_if.sv

TB_RAL_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/ral/smc_peripherals_ral_pkg.sv

VIP_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/vip/axi4lite_vip/axi4lite_vip_pkg.sv

CHECKER_PKG_SRC_FILES :=

TB_COV_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/coverage/smc_i3c_coverage_pkg.sv

TB_ENV_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/env/smc_peripherals_env_pkg.sv

TB_VSEQ_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/vseq/smc_peripherals_vseq_pkg.sv

TB_TEST_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/tests/smc_peripherals_test_pkg.sv

ORDERED_PKG_SRC_FILES := \
    $(ROOT_DIR)/verify/vip/axi4lite_vip/axi4lite_vip_pkg.sv \
    $(ROOT_DIR)/verify/tb/coverage/smc_i3c_coverage_pkg.sv \
    $(ROOT_DIR)/verify/tb/ral/smc_peripherals_ral_pkg.sv \
    $(ROOT_DIR)/verify/tb/env/smc_peripherals_env_pkg.sv \
    $(ROOT_DIR)/verify/tb/vseq/smc_peripherals_vseq_pkg.sv \
    $(ROOT_DIR)/verify/tb/tests/smc_peripherals_test_pkg.sv

SVA_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/sva/integration/smc_i3c_boundary_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/smc_i3c_ibi_bus_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/smc_i3c_ibi_controller_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/smc_i3c_ibi_protocol_sva.sv \
    $(ROOT_DIR)/verify/tb/sva/integration/smc_i3c_ibi_target_sva.sv

TB_TOP_SRC_FILES := \
    $(ROOT_DIR)/verify/tb/top/tb_smc_peripherals_top.sv

RTL_SRC_FILES := -f $(RTL_FLIST)

SRC_FILES := \
    $(TB_CORE_PKG_SRC_FILES) \
    $(VIP_IF_SRC_FILES) \
    $(ORDERED_PKG_SRC_FILES) \
    $(SVA_SRC_FILES) \
    $(TB_TOP_SRC_FILES) \
    $(RTL_SRC_FILES)
